name: ua-llm
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - transformers>=4.31.0
  - datasets>=2.14.4
  - openai==0.27.8
  - pre-commit==3.3.3
  - omegaconf==2.3.0
  - hydra-core==1.3.2
  - nltk==3.8.1
  - rouge_score==0.1.2
  - evaluate==0.4.0
  - cohere==4.21
  - replicate==0.11.0
