defaults:
  - _self_
  - /model: control

_target_: task.predict_task.PredictTask
model: control
reader:
  _target_: data.reader.csv_reader.CSVReader
  file_path: dataset/test.tsv
  delimiter: "\t"
writer:
  _target_: data.writer.csv_writer.CSVWriter
  file_path: dataset/predictions.tsv
  delimiter: "\t"
input_col: context
output_col: prediction
