defaults:
  - /task@model: qa_predict_task

_target_: task.eval_task.EvalTask
evaluator:
  _target_: eval.strings_eval.StringsEval
  methods:
    - exact
    - partial
    - any
    - bleu
    - rouge
    - squad_v2
reader:
  _target_: data.reader.csv_reader.CSVReader
  file_path: ${task.model.reader.file_path}
  delimiter: "\t"
writer:
  _target_: data.writer.csv_writer.CSVWriter
  file_path: dataset/examples/qa_eval.tsv
  delimiter: "\t"
input_col: answer
output_col: eval
