defaults:
  - /task@model: qa_predict_task

_target_: task.eval_task.EvalTask
evaluator:
  _target_: eval.strings_eval.StringsEval
  methods:
    - exact
    - partial
    - any
    - bleu
    - rouge
reader:
  _target_: data.reader.csv_reader.CSVReader
  file_path: dataset/gpt-4-turbo/en-ua-temp-0/squad_test_full.tsv
  delimiter: "\t"
writer:
  _target_: data.writer.csv_writer.CSVWriter
  file_path: dataset/gpt-4-turbo/en-ua-temp-0/squad_evals_full.tsv
  delimiter: "\t"
input_col: answer
output_col: eval
